# Generated by Django 4.2.1 on 2023-05-31 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="Cam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=4000)),
                ("title_color", models.CharField(max_length=7)),
                ("subtitle_color", models.CharField(max_length=7)),
                ("background_color", models.CharField(max_length=7)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cams.category"
                    ),
                ),
            ],
        ),
    ]
