# Generated by Django 4.2.1 on 2023-06-03 09:24

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Category = apps.get_model("cams", "Category")
    for i, category in enumerate(Category.objects.all()):
        category.order = i
        category.save()


class Migration(migrations.Migration):
    dependencies = [
        ("cams", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["order"], "verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(forwards_func),
    ]
