# Generated by Django 4.2.1 on 2023-05-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cam",
            name="category",
        ),
        migrations.AddField(
            model_name="cam",
            name="categories",
            field=models.ManyToManyField(to="cams.category"),
        ),
    ]
