# Generated by Django 4.2.1 on 2023-06-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cams", "0002_alter_category_options_category_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="cam",
            name="spot_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
