# Generated by Django 5.1.3 on 2025-04-14 00:44

from django.db import migrations, models


def migrate_to_proxy(apps, schema_editor):
    Cam = apps.get_model("cams", "Cam")
    cams_to_update = []
    for cam in Cam.objects.all():
        if cam.url and cam.url.startswith("/p/"):
            cam.proxy = True
            cam.url = cam.url.replace("/p/", "https://")
            cams_to_update.append(cam)

    if cams_to_update:
        Cam.objects.bulk_update(cams_to_update, ["proxy", "url"])


class Migration(migrations.Migration):
    dependencies = [
        ("cams", "0006_alter_cam_background_color_alter_cam_subtitle_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cam",
            name="proxy",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_to_proxy),
    ]
