# Generated by Django 5.1.3 on 2025-04-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cams", "0007_cam_proxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="cam",
            name="offline_since",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
